[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

board_build.partitions = no_ota.csv

lib_deps =
    knolleary/PubSubClient @ ^2.8   ; MQTT 客戶端
    robtillaart/MCP4725 @ ^0.4.3    ; DAC 調速模組（無額外依賴）
