[env:nodemcuv2]
platform  = espressif8266
board     = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed  = 460800

lib_deps =
    knolleary/PubSubClient @ ^2.8   ; MQTT 客戶端
    robtillaart/MCP4725 @ ^0.4.3    ; DAC 調速模組（無額外依賴）
